version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 999
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/London
    target-branch: main
    assignees:
      - ascopes
    labels:
      - dependencies

  - package-ecosystem: maven
    directories:
      - /
      - /protobuf-maven-plugin/src/it/setup
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/London
    open-pull-requests-limit: 999
    target-branch: main
    assignees:
      - ascopes
    labels:
      - dependencies
    ignore:
      # Maven versions should be kept in lockstep with the version
      # of Maven that is in use.
      - dependency-name: 'org.apache.maven.resolver:maven-resolver-api'
        versions:
          - '>=2.0.0'
      - dependency-name: 'org.apache.maven:maven-core'
        versions:
          - '>=4.0.0'
      - dependency-name: 'org.apache.maven:maven-plugin-api'
        versions:
          - '>=4.0.0'
      - dependency-name: 'org.apache.maven.plugin-tools:maven-plugin-annotations'
        versions:
          - '>=4.0.0'
